### ISSUE TITLE
Missing requirements.txt installation file

### ISSUE THREAD

**Issue by JCFactory** [kevinwu23/StanfordClashEval#1]
Hi Kevin, 

could you please add a requirements.txt for the versions of the used packages? 

It could look like this: 
requirements.txt:
`pandas
re
numpy
ast 
seaborn
matplotlib
IPython
warnings
requests
json
collections` 

It should include fixed versions otherwise the current available PyPi versions are loaded. 
Furthermore, I couldn't find `re` or `ast` package. Did you refer to the following packages: 
https://pypi.org/project/regex/
https://pypi.org/project/AST/
?

I am very pleased about your answer. 

Kind regards, Jacky

**Comment by kevinwu23** [comment]
Hi Jacky,
Thanks for using this repo! Yes, those packages are the correct references to ast and re, and we have included a requirements.txt.
